# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2023-01-13 16:46+0800\n"
"PO-Revision-Date: 2023-01-13 17:53+0800\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: en_US\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=cp936\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 3.2\n"

#: ../source\collector_flow.py:303
msgid "switch Flow to: AFTER_MOVETO_COLLECTOR"
msgstr ""

#: ../source\collector_flow.py:329
msgid "switch Flow to: BEFORE_PICKUP_COLLECTOR"
msgstr ""

#: ../source\collector_flow.py:337
msgid "switch Flow to: IN_PICKUP_COLLECTOR"
msgstr ""

#: ../source\collector_flow.py:347
msgid "switch Flow to: AFTER_PICKUP_COLLECTOR"
msgstr ""

#: ../source\combat_lib.py:84
msgid "获得当前角色编号失败"
msgstr "Failed to get the current character number"

#: ../source\combat_loop.py:65
msgid " 的Ecd_float_time大于0，请确定该角色不是多段e技能角色。"
msgstr "'s Ecd_float_time is greater than 0, please make sure that the character is not a character with multiple E skills."

#: ../source\combat_loop.py:65
msgid "角色 "
msgstr "character"

#: ../source\combat_loop.py:115
msgid "有人嘎了，停止自动战斗"
msgstr "Someone's dead, stop auto combat"

#: ../source\combat_loop.py:158 ../source\combat_loop.py:164
msgid "停止自动战斗"
msgstr "stop auto combat"

#: ../source\cvAutoTrack.py:103
msgid "cleaning cvautotrack files"
msgstr ""

#: ../source\cvAutoTrack.py:108
msgid "autoTrack.log 1 cleaned"
msgstr ""

#: ../source\cvAutoTrack.py:113
msgid "autoTrack.log 2 cleaned"
msgstr ""

#: ../source\cvAutoTrack.py:118
msgid "autoTrack.log 3 cleaned"
msgstr ""

#: ../source\cvAutoTrack.py:138
msgid "cvAutoTrack DLL has been loaded."
msgstr ""

#: ../source\domain_flow.py:38
msgid "请输入秘境次数"
msgstr "Please enter the number of challenges"

#: ../source\domain_flow.py:53
msgid "秘境次数："
msgstr "Challenge times:"

#: ../source\domain_flow.py:56
msgid "停止自动秘境"
msgstr "stop AutoDomain"

#: ../source\domain_flow.py:124
msgid "正在开始挑战秘境"
msgstr "Starting to challenge the domain"

#: ../source\domain_flow.py:274
msgid "正在开始战斗"
msgstr "starting combat"

#: ../source\domain_flow.py:288
msgid "正在停止战斗"
msgstr "stopting combat"

#: ../source\domain_flow.py:291
msgid "等待岩造物消失"
msgstr "Waiting for the rock-made to disappear"

#: ../source\domain_flow.py:299
msgid "正在激活石化古树"
msgstr "Activating the tree"

#: ../source\domain_flow.py:344
msgid "秘境结束。"
msgstr "Domain over."

#: ../source\domain_flow.py:355
msgid "开始下一次秘境"
msgstr "Starting next domain"

#: ../source\domain_flow.py:371
msgid "次数结束。退出秘境"
msgstr "The number of times is over. Exit the domain"

#: ../source\flow_state.py:91
msgid "空闲"
msgstr "Idle"

#: ../source\flow_state.py:94
msgid "正在初始化"
msgstr "Initializing"

#: ../source\flow_state.py:96
msgid "正在准备"
msgstr "Prepareing"

#: ../source\flow_state.py:98
msgid "正在进行"
msgstr "Doing"

#: ../source\flow_state.py:100
msgid "准备结束"
msgstr "Ready to end"

#: ../source\flow_state.py:102
msgid "结束"
msgstr "End"

#: ../source\flow_state.py:105
msgid "移动到挑战位置"
msgstr "move to challenge position"

#: ../source\flow_state.py:107
msgid "挑战秘境中"
msgstr "In challenging"

#: ../source\flow_state.py:109
msgid "准备领取奖励"
msgstr "ready to claim reward"

#: ../source\flow_state.py:111
msgid "正在寻找石化古树位置"
msgstr "Looking for the location of the tree"

#: ../source\flow_state.py:113
msgid "移动到石化古树位置"
msgstr "Move to the location of the tree"

#: ../source\flow_state.py:115
msgid "领取奖励"
msgstr "Obtain reaward"

#: ../source\flow_state.py:117
msgid "结束秘境"
msgstr "End domain"

#: ../source\flow_state.py:119
msgid "在地图上传送"
msgstr "teleport on map"

#: ../source\flow_state.py:121
msgid "移动到目标坐标位置"
msgstr "Move to the target coordinate position"

#: ../source\flow_state.py:123
msgid "移动到采集物位置"
msgstr "Move to collection location"

#: ../source\flow_state.py:125
msgid "拾取采集物"
msgstr "Pick up collection"

#: ../source\flow_state.py:127
msgid "结束自动采集"
msgstr "End AutoCollection"

#: ../source\generic_lib.py:72 ../source\teyvat_move_flow.py:157
msgid "获取传送锚点失败，正在重试"
msgstr "Failed to get teleportation, retrying"

#: ../source\interaction_background.py:43
msgid "恢复操作"
msgstr "recovery operation"

#: ../source\interaction_background.py:45
msgid "当前窗口焦点为"
msgstr "The current window focus is"

#: ../source\listening.py:55
msgid "Program stop."
msgstr ""

#: ../source\listening.py:60
msgid "正在停止自动战斗"
msgstr "Stopping AutoCombat"

#: ../source\listening.py:64
msgid "启动自动战斗"
msgstr "Start AutoCombat"

#: ../source\listening.py:74
msgid "正在停止自动秘境"
msgstr "Stoping AutoDomain"

#: ../source\listening.py:78
msgid "启动自动秘境"
msgstr "Start AutoDomain"

#: ../source\listening.py:87
msgid "正在停止自动采集"
msgstr "Stoping AutoCollector"

#: ../source\listening.py:90
msgid "启动自动采集"
msgstr "Start AutoCollector"

#: ../source\listening.py:134
msgid "导入完成"
msgstr "Import complete"

#: ../source\pdocr_api.py:3
msgid "Creating ocr object."
msgstr ""

#: ../source\pdocr_api.py:14
msgid "导入paddleocr时错误; err code: 001"
msgstr "Error when importing paddleocr; err code: 001"

#: ../source\pdocr_api.py:40
msgid "ocr device: "
msgstr ""

#: ../source\pickup_operator.py:53
msgid "正在设置时间为夜晚"
msgstr "Setting time to night"

#: ../source\pickup_operator.py:80
msgid "停止自动拾取"
msgstr "Stop AutoCollector"

#: ../source\pickup_operator.py:113
msgid "PICKUP_TIMEOUT_001"
msgstr ""

#: ../source\pickup_operator.py:115 ../source\pickup_operator.py:121
msgid "停止拾取"
msgstr "Stop pickup"

#: ../source\pickup_operator.py:119
msgid "PICKUP_TIMEOUT_002"
msgstr ""

#: ../source\pickup_operator.py:128
msgid "已找到物品且无法找到下一个物品，停止拾取"
msgstr "Item found and can't find next item, stop picking"

#: ../source\pickup_operator.py:161
msgid "pickup: "
msgstr ""

#: ../source\pickup_operator.py:163
msgid "已找到："
msgstr "Found"

#: ../source\scene_manager.py:66
msgid "UI界面检测失败，正在尝试按esc返回"
msgstr "UI interface detection failed, trying to press esc to return"

#: ../source\scene_manager.py:68
msgid "将在1秒后再次尝试获取UI界面"
msgstr "Will try to get the UI again after 1 second"

#: ../source\scene_manager.py:69 ../source\scene_manager.py:75
msgid "尝试次数："
msgstr "Retry times:"

#: ../source\scene_manager.py:73
msgid "UI界面检测失败"
msgstr "UI interface detection failed"

#: ../source\scene_manager.py:74
msgid "将在0.2秒后再次尝试获取UI界面"
msgstr "Will try to get the UI again after 0.2 seconds"

#: ../source\static_lib.py:32
msgid "等待cvautotrack获取坐标"
msgstr "Wait for cvautotrack to get the coordinates"

#: ../source\teyvat_move_controller.py:138
msgid "已到达目的地附近，本次导航结束。"
msgstr "Near the destination has been reached, this navigation is over."

#: ../source\teyvat_move_controller.py:143
msgid "已到达F附近，本次导航结束。"
msgstr "You have reached the button of F, and this navigation is over."

#: ../source\teyvat_move_flow.py:121
msgid "停止自动移动"
msgstr "Stop AutoMove"

#: ../source\teyvat_move_flow.py:268
msgid "正在落地"
msgstr "Landing"

#: ../source\teyvat_move_flow.py:270
msgid "结束自动行走"
msgstr "Stop AutoMove"

#: ../source\util.py:80 ../source\util.py:82
msgid " 请检查"
msgstr "Please check up"

#: ../source\util.py:80 ../source\util.py:82
msgid "目录不存在："
msgstr "Directory does not exist:"

#: ../source\util.py:95
msgid "请用管理员权限运行"
msgstr "Please run with administrator level"

#: ../source\yolox_api.py:6
msgid "Creating yolox obj. It may takes a few second."
msgstr ""

#: ../source\yolox_api.py:23
msgid "导入torch时错误; err code: 002"
msgstr "Error when importing torch; err code: 002"

#: ../source\yolox_api.py:535
msgid "Created yolox obj."
msgstr ""

